### PR TITLE
598 dispense status

### PR DESCRIPTION
**Pull request by avirgulto**
## Describe your changes

Update to call the test-ehr new endpoint /MedicationDispense?prescription=<id> when looking for pharmacy status instead of hitting pims to getRx status. Currently, the status is complete when complete or nothing/unknown at all other times. Use with the test-ehr branch 'rxfill' unless that PR gets merged in before this.  

## Issue ticket number and Jira link

https://jira.mitre.org/browse/REMS-598

## Checklist before requesting a review
- [ ] I have performed a self-review of my code
- [ ] Ensure the target / base branch for any feature PR is set to `dev` not main (the only exception to this is releases from `dev` and hotfix branches)

## Checklist for conducting a review
- [ ] Review the code changes and make sure they all make sense and are necessary. 
- [ ] Pull the PR branch locally and test by running through workflow and making sure everything works as it is supposed to. 

## Workflow 

Owner of the Pull Request will be responsible for merge after all requirements are met, including approval from at least one reviewer. Additional changes made after a review will dismiss any approvals and require re-review of the additional updates. Auto merging can be enabled below if additional changes are likely not to be needed. The bot will auto assign reviewers to your Pull Request for you.

### CODE REVIEW

**Comment by avirgulto** [comment]
Screenshot 2024-02-12 at 11 12 15 AM
Screenshot 2024-02-12 at 11 12 27 AM
Screenshot 2024-02-12 at 11 12 55 AM
Current UI changes, unsure if we want to change the Pharmacy to medication or something since we've changed pharmacy status to medication status?

**Comment by plarocque4** [comment]
Should the Medication Status box in the page that is displayed after the patient enrollment form is completed allow for a refresh to check if the medication status has updated?

**Comment by avirgulto** [comment]
> Should the Medication Status box in the page that is displayed after the patient enrollment form is completed allow for a refresh to check if the medication status has updated?

Yeah sure, I can add in a refresh button to it!

**Review by plarocque4 — APPROVED** [review]
Looks good!

**Pull request merged**
