### PR TITLE
Rearrange SMART on FHIR App UI

### PR DESCRIPTION
**Pull request by jtquach1**
Related Jira ticket: https://jira.mitre.org/browse/REMS-414

### CODE REVIEW

**Comment by jtquach1** [comment]
# Screenshots (after) on iPad Mini simulated device:

## Two horizontal panes
image

image

image

## Two vertical panes
image

image

image

**Review by avirgulto — APPROVED** [review]
Looked over the code and the UI, everything looks good to me! I like the new style design.

**Comment by plarocque4** [comment]
When the page is wide, should the patient information be 50% like we have now? Or should it be smaller with maybe a fixed maximum size since it's not the focus of the interface, it's really there for information purposes. The text "Launched with patient context:" should perhaps be smaller and just over the "Patient Info" section? We should discuss this at standup. 
Overall it looks and works great though!

**Comment by jtquach1** [comment]
# Current (after) screenshots
image
image

image
image


# Changes made
- Reduced the ratio from 50:50 to 25:75 for the patient info and medication request panes
- Added spacing between CDS Hooks Card buttons 
- Moved Grid component out of the medication request dropdown component

**Pull request merged**
