### PR TITLE
CDS Hook Cards UI Updates 

### PR DESCRIPTION
**Pull request by zacharyrobin**
## Describe your changes

Updated CDS Hooks Card UI based off of mockup styling. 

Old: 
Screenshot 2024-04-12 at 7 48 58 AM

Updated:

 
Screenshot 2024-04-12 at 7 49 39 AM

## Issue ticket number and Jira link

[REMS-579](https://jira.mitre.org/browse/REMS-579)

## Checklist before requesting a review
- [x ] I have performed a self-review of my code
- [x ] Ensure the target / base branch for any feature PR is set to `dev` not main (the only exception to this is releases from `dev` and hotfix branches)

## Checklist for conducting a review
- [ ] Review the code changes and make sure they all make sense and are necessary. 
- [ ] Pull the PR branch locally and test by running through workflow and making sure everything works as it is supposed to. 

## Workflow 

Owner of the Pull Request will be responsible for merge after all requirements are met, including approval from at least one reviewer. Additional changes made after a review will dismiss any approvals and require re-review of the additional updates. Auto merging can be enabled below if additional changes are likely not to be needed. The bot will auto assign reviewers to your Pull Request for you.

### CODE REVIEW

**Comment by KeeyanGhoreshi** [comment]
Looks fine and works as is, the only thing I'll mention is that I think we could maybe get it to look a little nicer by adopting a more "square" look for the card internals, to avoid stacking all the options on top of each other.  When the cards are side by side, they have a difference in height of components so you're left with a big gap on the bottom of one of them, for example:
image

It might look a bit more homogenous if we have them square so they line up into the same row.  I'm also a big proponent of getting rid of the "Add ____ to task list" from the task buttons if they're going to be under a section called "Add to task list".

**Comment by KeeyanGhoreshi** [comment]
just needs linting errors fixed

**Review by plarocque4 — COMMENTED** [review]
It would be nice to hide the document list if there are no documents available.

**Review by plarocque4 — APPROVED** [review]

**Review by plarocque4 — APPROVED** [review]
looks good

**Pull request merged**
